/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConfigSchema {
  /**
   * 共通設定
   */
  commonSettings: {
    /**
     * Slackボットのトークン
     */
    slackBotToken: string;
    /**
     * エラー時の通知用Webhook URL
     */
    errorNotificationWebhook: string;
    [k: string]: unknown;
  };
  /**
   * 複数の通知設定
   */
  notificationSettings: {
    /**
     * 対象のレコード一覧のID
     */
    recordListId: string;
    /**
     * 通知ボタンの表示名
     */
    buttonName?: string;
    /**
     * 通知先のSlackチャンネルID
     */
    slackChannelId: string;
    /**
     * チャンネルに招待するユーザーのIDのフィールド
     */
    slackIdField?: string[];
    messageTemplate: {
      /**
       * メッセージタイトル
       */
      title: string;
      /**
       * メッセージ本文
       */
      body: string;
      /**
       * メッセージフッター
       */
      footer: string;
      [k: string]: unknown;
    };
    /**
     * 通知後にリンクを入力するフィールド名
     */
    notificationLinkField: string;
    /**
     * 通知日時を入力するフィールド名
     */
    notificationDateTimeField?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
